from setuptools import setup, find_packages

setup(
    name="theta-ai-backend",
    version="1.0.0",
    packages=find_packages(),
    install_requires=[
        "fastapi>=0.104.0",
        "uvicorn>=0.24.0",
        "sqlalchemy>=2.0.0",
        "asyncpg>=0.29.0",
        "redis>=5.0.0",
        "pydantic>=2.5.0",
        "alembic>=1.12.0",
        "python-jose>=3.3.0",
        "passlib>=1.7.4",
        "python-multipart>=0.0.6",
        "httpx>=0.25.0",
        "websockets>=12.0",
        "prometheus-client>=0.19.0",
        "opentelemetry-api>=1.21.0",
        "opentelemetry-sdk>=1.21.0",
        "structlog>=23.2.0",
        "colorlog>=6.7.0",
        "pyyaml>=6.0.1",
        "python-dotenv>=1.0.0",
    ],
    python_requires=">=3.9",
)